#############################################################################
# Makefile for building: bin/qxkb
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? ????. 22 11:05:26 2010
# Project:  QXKB.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile QXKB.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -Ibuild -I. -I/usr/include -I/usr/include/QxtGui -I/usr/include/QxtCore
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lxkbfile -lQxtCore -lQxtGui -lQtSvg -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/qxkb.cpp \
		src/xkeyboard.cpp \
		src/xkbconf.cpp \
		src/x11tools.cpp \
		src/main.cpp \
		src/datamodels.cpp \
		src/about.cpp build/moc_qxkb.cpp \
		build/moc_xkeyboard.cpp \
		build/moc_xkbconf.cpp \
		build/moc_datamodels.cpp \
		build/moc_about.cpp \
		qrc_icon.cpp
OBJECTS       = build/qxkb.o \
		build/xkeyboard.o \
		build/xkbconf.o \
		build/x11tools.o \
		build/main.o \
		build/datamodels.o \
		build/about.o \
		build/moc_qxkb.o \
		build/moc_xkeyboard.o \
		build/moc_xkbconf.o \
		build/moc_datamodels.o \
		build/moc_about.o \
		build/qrc_icon.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QXKB.pro
QMAKE_TARGET  = qxkb
DESTDIR       = bin/
TARGET        = bin/qxkb

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_kswconfig.h ui_about.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QXKB.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSvg.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile QXKB.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSvg.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile QXKB.pro

dist: 
	@$(CHK_DIR_EXISTS) build/qxkb0.4.3-pre || $(MKDIR) build/qxkb0.4.3-pre 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/qxkb0.4.3-pre/ && $(COPY_FILE) --parents src/qxkb.h src/xkeyboard.h src/xkbconf.h src/x11tools.h src/datamodels.h src/defs.h src/about.h build/qxkb0.4.3-pre/ && $(COPY_FILE) --parents qrc/icon.qrc build/qxkb0.4.3-pre/ && $(COPY_FILE) --parents src/qxkb.cpp src/xkeyboard.cpp src/xkbconf.cpp src/x11tools.cpp src/main.cpp src/datamodels.cpp src/about.cpp build/qxkb0.4.3-pre/ && $(COPY_FILE) --parents ui/kswconfig.ui ui/about.ui build/qxkb0.4.3-pre/ && $(COPY_FILE) --parents language/qxkb_ru.ts build/qxkb0.4.3-pre/ && (cd `dirname build/qxkb0.4.3-pre` && $(TAR) qxkb0.4.3-pre.tar qxkb0.4.3-pre && $(COMPRESS) qxkb0.4.3-pre.tar) && $(MOVE) `dirname build/qxkb0.4.3-pre`/qxkb0.4.3-pre.tar.gz . && $(DEL_FILE) -r build/qxkb0.4.3-pre


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) qxkb
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_qxkb.cpp build/moc_xkeyboard.cpp build/moc_xkbconf.cpp build/moc_datamodels.cpp build/moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_qxkb.cpp build/moc_xkeyboard.cpp build/moc_xkbconf.cpp build/moc_datamodels.cpp build/moc_about.cpp
build/moc_qxkb.cpp: src/defs.h \
		src/xkeyboard.h \
		src/x11tools.h \
		src/xkbconf.h \
		src/datamodels.h \
		ui_kswconfig.h \
		src/about.h \
		ui_about.h \
		src/convert.h \
		src/qxkb.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qxkb.h -o build/moc_qxkb.cpp

build/moc_xkeyboard.cpp: src/defs.h \
		src/xkeyboard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/xkeyboard.h -o build/moc_xkeyboard.cpp

build/moc_xkbconf.cpp: src/defs.h \
		src/x11tools.h \
		src/datamodels.h \
		ui_kswconfig.h \
		src/xkbconf.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/xkbconf.h -o build/moc_xkbconf.cpp

build/moc_datamodels.cpp: src/defs.h \
		src/x11tools.h \
		src/datamodels.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/datamodels.h -o build/moc_datamodels.cpp

build/moc_about.cpp: src/defs.h \
		ui_about.h \
		src/about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/about.h -o build/moc_about.cpp

compiler_rcc_make_all: qrc_icon.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icon.cpp
qrc_icon.cpp: qrc/icon.qrc \
		qrc/qxkb.png \
		qrc/qt.png
	/usr/bin/rcc -name icon qrc/icon.qrc -o qrc_icon.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_kswconfig.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_kswconfig.h ui_about.h
ui_kswconfig.h: ui/kswconfig.ui
	/usr/bin/uic-qt4 ui/kswconfig.ui -o ui_kswconfig.h

ui_about.h: ui/about.ui
	/usr/bin/uic-qt4 ui/about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/qxkb.o: src/qxkb.cpp src/qxkb.h \
		src/defs.h \
		src/xkeyboard.h \
		src/x11tools.h \
		src/xkbconf.h \
		src/datamodels.h \
		ui_kswconfig.h \
		src/about.h \
		ui_about.h \
		src/convert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qxkb.o src/qxkb.cpp

build/xkeyboard.o: src/xkeyboard.cpp src/xkeyboard.h \
		src/defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/xkeyboard.o src/xkeyboard.cpp

build/xkbconf.o: src/xkbconf.cpp src/xkbconf.h \
		src/defs.h \
		src/x11tools.h \
		src/datamodels.h \
		ui_kswconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/xkbconf.o src/xkbconf.cpp

build/x11tools.o: src/x11tools.cpp src/x11tools.h \
		src/defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/x11tools.o src/x11tools.cpp

build/main.o: src/main.cpp src/defs.h \
		src/qxkb.h \
		src/xkeyboard.h \
		src/x11tools.h \
		src/xkbconf.h \
		src/datamodels.h \
		ui_kswconfig.h \
		src/about.h \
		ui_about.h \
		src/convert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/datamodels.o: src/datamodels.cpp src/datamodels.h \
		src/defs.h \
		src/x11tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/datamodels.o src/datamodels.cpp

build/about.o: src/about.cpp src/about.h \
		src/defs.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/about.o src/about.cpp

build/moc_qxkb.o: build/moc_qxkb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_qxkb.o build/moc_qxkb.cpp

build/moc_xkeyboard.o: build/moc_xkeyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_xkeyboard.o build/moc_xkeyboard.cpp

build/moc_xkbconf.o: build/moc_xkbconf.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_xkbconf.o build/moc_xkbconf.cpp

build/moc_datamodels.o: build/moc_datamodels.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_datamodels.o build/moc_datamodels.cpp

build/moc_about.o: build/moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_about.o build/moc_about.cpp

build/qrc_icon.o: qrc_icon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_icon.o qrc_icon.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "bin/$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_translations: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/qt4/translations/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/qt4/translations/ 
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)// || $(MKDIR) $(INSTALL_ROOT)// 
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/qt4/translations/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/qt4/translations/ 
	-$(INSTALL_PROGRAM) /media/atlas_h/Project/DE/qxkb/language/qxkb_ru.qm $(INSTALL_ROOT)/usr/share/qt4/translations/
	-strip $(INSTALL_ROOT)/usr/share/qt4/translations/qxkb_ru.qm


uninstall_translations:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/qxkb_ru.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/qt4/translations/ 


install_theme: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/qxkb/theme/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/qxkb/theme/ 
	-$(INSTALL_DIR) /media/atlas_h/Project/DE/qxkb/theme/default $(INSTALL_ROOT)/usr/share/qxkb/theme/


uninstall_theme:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qxkb/theme/default
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/qxkb/theme/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_PROGRAM) /media/atlas_h/Project/DE/qxkb/desktop/qxkb.desktop $(INSTALL_ROOT)/usr/share/applications/
	-strip $(INSTALL_ROOT)/usr/share/applications/qxkb.desktop


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/qxkb.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/pixmaps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 
	-$(INSTALL_PROGRAM) /media/atlas_h/Project/DE/qxkb/desktop/qxkb.png $(INSTALL_ROOT)/usr/share/pixmaps/
	-strip $(INSTALL_ROOT)/usr/share/pixmaps/qxkb.png


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/qxkb.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 


install:  install_target install_translations install_theme install_desktop install_icon  FORCE

uninstall: uninstall_target uninstall_translations uninstall_theme uninstall_desktop uninstall_icon   FORCE

FORCE:

